### ISSUE TITLE
nse-script output goes outside of the page

### ISSUE THREAD

**Issue by vdjagilev** [vdjagilev/nmap-formatter#112]
```css
.data-table > tbody > tr > td > pre
{
  word-break: break-word;
}
```
