### ISSUE TITLE
Alternative golangci-lint 

### ISSUE THREAD

**Issue by vdjagilev** [vdjagilev/nmap-formatter#69]
```yaml
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
```
