### ISSUE TITLE
Make a build matrix for different platforms

### ISSUE THREAD

**Issue by vdjagilev** [vdjagilev/nmap-formatter#9]
https://github.com/mvdan/github-actions-golang

```yml
on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
```
